name: Example
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI CLI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          pipeline: .
          args: push push:sqlite
          working-directory: turso-example
        env:
          DATABASE_URL: libsql://regular-greymalkin-tsirysndr.turso.io
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}

      - name: Run Dagger Pipelines (Turso Example)
        run: |
          rm ../deno.lock
          dagger run deno run -A ../src/dagger/runner.ts
        working-directory: turso-example
        env:
          DATABASE_URL: libsql://regular-greymalkin-tsirysndr.turso.io
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
      - name: Run Dagger Pipelines
        run: dagger run deno run -A ../src/dagger/runner.ts
        working-directory: example
        env:
          DATABASE_URL: postgres://postgres:pass@postgres:5432/example
